#%RAML 1.0 NamedExample
  [
    {
        "ENTERPRISE_ADDRESS_NUMBER_CDH": "815500",
        "ENTERPRISE_ACCOUNT_NUMBER_CDH": "567056",
        "NAME_CDH": "ETF",
        "IS_SOLD_TO_CDH": "0",
        "ACCOUNT_OWNER": "Peter Lenk",
        "CHANNEL_PARTNER": "Projet Lineaire",
        "ACCOUNT_NAME": "ETF",
        "TYPE_CDH": "Organization",
        "BILLING_ZIP": null,
        "CITY_CDH": null,
        "IS_END_USER_CDH": "0",
        "WEBSITE": null,
        "IS_SHIP_TO_CDH": "1",
        "IS_INSTALLED_AT_CDH": "0",
        "BILLING_COUNTRY": "France",
        "PARENT_ACCOUNT": "Projet Lineaire",
        "BILLING_STREET": "267, Chaussee Jules Cesar",
        "BILLING_CITY": "Beauchamp",
        "IS_BILL_TO_CDH": "0",
        "ACCOUNT_ID": "0014U000028rojZ",
        "PHONE": null,
        "ZIP_CDH": null,
        "ADDRESS_LINE1_CDH": "XX",
        "APE_ID": 4175,
        "B2B_CDH": "Customer",
        "COUNTRY_CDH": "FR"
    },
    {
        "ENTERPRISE_ADDRESS_NUMBER_CDH": "801299",
        "ENTERPRISE_ACCOUNT_NUMBER_CDH": "553049",
        "NAME_CDH": "ETF",
        "IS_SOLD_TO_CDH": "0",
        "ACCOUNT_OWNER": "Peter Lenk",
        "CHANNEL_PARTNER": "Projet Lineaire",
        "ACCOUNT_NAME": "ETF",
        "TYPE_CDH": "Organization",
        "BILLING_ZIP": null,
        "CITY_CDH": null,
        "IS_END_USER_CDH": "0",
        "WEBSITE": null,
        "IS_SHIP_TO_CDH": "1",
        "IS_INSTALLED_AT_CDH": "0",
        "BILLING_COUNTRY": "France",
        "PARENT_ACCOUNT": "Projet Lineaire",
        "BILLING_STREET": "267, Chaussee Jules Cesar",
        "BILLING_CITY": "Beauchamp",
        "IS_BILL_TO_CDH": "0",
        "ACCOUNT_ID": "0014U000028rojZ",
        "PHONE": null,
        "ZIP_CDH": null,
        "ADDRESS_LINE1_CDH": "Rue de Meunynck",
        "APE_ID": 4175,
        "B2B_CDH": "Customer",
        "COUNTRY_CDH": "FR"
    }
]